Port: 8080
{
  "prediction": [
    20.35373177134412
  ]
}




(.devops) funmibi@IMBIL-LT5:/mnt/c/users/lptng2/Desktop/project4$ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "ml-api" already exists
NAME     READY   STATUS    RESTARTS   AGE
ml-api   1/1     Running   0          102m
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
Handling connection for 8080


 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 153-178-840
[2022-08-09 09:35:16,605] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-08-09 09:35:16,712] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 09:35:16,751] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 09:35:16,779] INFO in app: output prediction:
[20.35373177134412]
172.17.0.1 - - [09/Aug/2022 09:35:16] "POST /predict HTTP/1.1" 200 -

[2022-08-09 09:35:16,605] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-08-09 09:35:16,712] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 09:35:16,751] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-09 09:35:16,779] INFO in app: output prediction:
[20.35373177134412]
172.17.0.1 - - [09/Aug/2022 09:35:16] "POST /predict HTTP/1.1" 200 -